"""Baseline — the complete schema as it stood at the end of Phase 9.5.

**This revision is a starting line, not a change.** It was autogenerated against
an empty database from the models, so running it builds all seventeen tables from
nothing. But every database that existed before Phase 10 already has that shape,
so those are `stamp`ed at this revision instead — the version row is written and
no DDL runs at all. See `app/db/migrate.py` for the three cases.

**Why the whole schema is one revision rather than nine reconstructed ones.**
Alembic could have been given a revision per historical phase, replaying Phases
1-9.5 as migrations. That would be fiction: those changes were never applied that
way, the scripts would have been written after the fact and never run against a
real database in that order, and the only thing they would protect is a
hypothetical database that does not exist. A baseline states what is true — this
is the schema — and the history of how it got here lives in the changelog and in
git, which are the right places for it.

`downgrade()` drops everything, which is the honest inverse of "create
everything". It is not a step anyone should run against a database they care
about, and `test_every_revision_has_a_downgrade` exists to make sure later
revisions have a *useful* one.

Revision ID: 0001
Revises:
Create Date: 2026-09-08 06:26:12.337021
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('color_key', sa.String(length=24), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(length=40), nullable=False),
    sa.Column('target_language', sa.String(length=40), nullable=False),
    sa.Column('flag_emoji', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_user_id', ['user_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('color_key', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'order_index', name='uq_unit_order_in_course')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index('ix_units_course_id', ['course_id'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index('ix_user_achievements_user_id', ['user_id'], unique=False)

    op.create_table('user_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('gems', sa.Integer(), nullable=False),
    sa.Column('hearts', sa.Integer(), nullable=False),
    sa.Column('hearts_updated_at', sa.DateTime(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('daily_goal', sa.Integer(), nullable=False),
    sa.Column('daily_xp', sa.Integer(), nullable=False),
    sa.CheckConstraint('hearts >= 0 AND hearts <= 5', name='ck_user_stats_hearts'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'order_index', name='uq_skill_order_in_unit')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index('ix_skills_unit_id', ['unit_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'order_index', name='uq_lesson_order_in_skill')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index('ix_lessons_skill_id', ['skill_id'], unique=False)

    op.create_table('placement_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_level', sa.Integer(), nullable=True),
    sa.Column('result_score', sa.Integer(), nullable=True),
    sa.Column('result_max_score', sa.Integer(), nullable=True),
    sa.Column('result_skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('placement_tests', schema=None) as batch_op:
        batch_op.create_index('ix_placement_tests_user_id', ['user_id'], unique=False)

    op.create_table('user_onboarding',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('proficiency', sa.Enum('BEGINNER', 'COMMON_WORDS', 'BASIC_CONVERSATION', 'VARIOUS_TOPICS', 'ADVANCED', name='ck_proficiency_level', native_enum=False, create_constraint=True, length=24), nullable=True),
    sa.Column('starting_mode', sa.Enum('SCRATCH', 'PLACEMENT', name='ck_starting_mode', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('placement_level', sa.Integer(), nullable=True),
    sa.Column('placement_skill_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['placement_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_onboarding', schema=None) as batch_op:
        batch_op.create_index('ix_user_onboarding_course_id', ['course_id'], unique=False)

    op.create_table('user_skill_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('lessons_completed', sa.Integer(), nullable=False),
    sa.Column('crowns', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(), nullable=True),
    sa.Column('placed_out_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_progress_user_skill')
    )
    with op.batch_alter_table('user_skill_progress', schema=None) as batch_op:
        batch_op.create_index('ix_user_skill_progress_skill_id', ['skill_id'], unique=False)
        batch_op.create_index('ix_user_skill_progress_user_id', ['user_id'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MULTIPLE_CHOICE', 'TRANSLATE', 'MATCH_PAIRS', 'FILL_BLANK', 'TYPE_ANSWER', name='ck_exercise_type', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'order_index', name='uq_exercise_order_in_lesson')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index('ix_exercises_lesson_id', ['lesson_id'], unique=False)

    op.create_table('lesson_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('incorrect_answers', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('hearts_lost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_lesson_attempts_lesson_id', ['lesson_id'], unique=False)
        batch_op.create_index('ix_lesson_attempts_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_lesson_attempts_user_lesson', ['user_id', 'lesson_id'], unique=False)

    op.create_table('lesson_attempt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('submitted', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('hearts_lost', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['lesson_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'exercise_id', name='uq_answer_attempt_exercise')
    )
    with op.batch_alter_table('lesson_attempt_answers', schema=None) as batch_op:
        batch_op.create_index('ix_lesson_attempt_answers_attempt_id', ['attempt_id'], unique=False)

    op.create_table('lesson_attempt_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('left_id', sa.String(length=32), nullable=False),
    sa.Column('right_id', sa.String(length=32), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('hearts_lost', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['lesson_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'exercise_id', 'left_id', 'right_id', name='uq_pair_attempt_exercise_pair')
    )
    with op.batch_alter_table('lesson_attempt_pairs', schema=None) as batch_op:
        batch_op.create_index('ix_lesson_attempt_pairs_attempt_exercise', ['attempt_id', 'exercise_id'], unique=False)

    op.create_table('placement_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('submitted', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['placement_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'exercise_id', name='uq_placement_answer_test_exercise')
    )
    with op.batch_alter_table('placement_answers', schema=None) as batch_op:
        batch_op.create_index('ix_placement_answers_test_id', ['test_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_placement_answers_test_id')

    op.drop_table('placement_answers')
    with op.batch_alter_table('lesson_attempt_pairs', schema=None) as batch_op:
        batch_op.drop_index('ix_lesson_attempt_pairs_attempt_exercise')

    op.drop_table('lesson_attempt_pairs')
    with op.batch_alter_table('lesson_attempt_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_lesson_attempt_answers_attempt_id')

    op.drop_table('lesson_attempt_answers')
    with op.batch_alter_table('lesson_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_lesson_attempts_user_lesson')
        batch_op.drop_index('ix_lesson_attempts_user_id')
        batch_op.drop_index('ix_lesson_attempts_lesson_id')

    op.drop_table('lesson_attempts')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index('ix_exercises_lesson_id')

    op.drop_table('exercises')
    with op.batch_alter_table('user_skill_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_user_skill_progress_user_id')
        batch_op.drop_index('ix_user_skill_progress_skill_id')

    op.drop_table('user_skill_progress')
    with op.batch_alter_table('user_onboarding', schema=None) as batch_op:
        batch_op.drop_index('ix_user_onboarding_course_id')

    op.drop_table('user_onboarding')
    with op.batch_alter_table('placement_tests', schema=None) as batch_op:
        batch_op.drop_index('ix_placement_tests_user_id')

    op.drop_table('placement_tests')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index('ix_lessons_skill_id')

    op.drop_table('lessons')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index('ix_skills_unit_id')

    op.drop_table('skills')
    op.drop_table('user_stats')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index('ix_user_achievements_user_id')

    op.drop_table('user_achievements')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index('ix_units_course_id')

    op.drop_table('units')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_id')

    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('courses')
    op.drop_table('achievements')
    # ### end Alembic commands ###
